#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
    local enabled

    config_load icenetwork_esp
    config_get enabled main enabled '1'
    [ "$enabled" = '1' ] || return 0

    procd_open_instance
    procd_set_param command /usr/sbin/icenetwork_esp_reporter.sh
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger icenetwork_esp
}
